# create docx from file structure

$ROOT_PATH = Split-Path $PSScriptRoot
$SRC_PATH = [IO.Path]::Combine($ROOT_PATH, "autogenerated")
$TARGET_PATH = [IO.Path]::Combine($ROOT_PATH, "src")
$NAME = "MILAXON_REC-MA4000-UM_Rev0"
$SRC = Join-Path $SRC_PATH $NAME
$TARGET = Join-Path $TARGET_PATH $NAME

# remove files that will be created
if (Test-Path "$TARGET.docx") {
	Remove-Item "$TARGET.docx" -verbose
}
if (Test-Path "$TARGET.zip") {
	Remove-Item "$TARGET.zip" -verbose
}

# zip
Compress-Archive "$SRC\*" "$TARGET.zip"

# change name 
Rename-Item "$TARGET.zip" "$TARGET.docx"
